local _, NS = ...;

NS.SPELLCATEGORY = {
    OFFENSIVE = 1,

    INTERRUPT = 2,
    DISRUPT = 3,
    CROWDCONTROL = 4,
    DISPEL = 5,
    DEFENSIVE = 6,
}

NS.SPECID = {
    ARCANE = 62,
    RET = 70,
    BALANCE = 102,
    FERAL = 103,
    BM = 253,
    WW = 269,
    DEVASTATION = 1467,
}

-- Event name constants
NS.PLAYER_ENTERING_WORLD = "PLAYER_ENTERING_WORLD"
NS.ARENA_PREP_OPPONENT_SPECIALIZATIONS = "ARENA_PREP_OPPONENT_SPECIALIZATIONS"
NS.PLAYER_SPECIALIZATION_CHANGED = "PLAYER_SPECIALIZATION_CHANGED"
NS.UNIT_SPELLCAST_SUCCEEDED = "UNIT_SPELLCAST_SUCCEEDED"
NS.UNIT_AURA = "UNIT_AURA"
NS.COMBAT_LOG_EVENT_UNFILTERED = "COMBAT_LOG_EVENT_UNFILTERED"
NS.GROUP_ROSTER_UPDATE = "GROUP_ROSTER_UPDATE"
NS.NAME_PLATE_UNIT_ADDED = "NAME_PLATE_UNIT_ADDED"
NS.NAME_PLATE_UNIT_REMOVED = "NAME_PLATE_UNIT_REMOVED"
-- Sub event name constants
NS.SPELL_CAST_SUCCESS = "SPELL_CAST_SUCCESS"
NS.SPELL_AURA_APPLIED = "SPELL_AURA_APPLIED"
NS.SPELL_AURA_REMOVED = "SPELL_AURA_REMOVED"
NS.SPELL_DAMAGE = "SPELL_DAMAGE"
NS.SPELL_CAST_START = "SPELL_CAST_START"
NS.SPELL_SUMMON = "SPELL_SUMMON"
NS.UNIT_DIED = "UNIT_DIED"
NS.UNIT_TARGET = "UNIT_TARGET";

-- classFileName constants
NS.DEATHKNIGHT = "DEATHKNIGHT";
NS.DEMONHUNTER = "DEMONHUNTER";
NS.DRUID = "DRUID";
NS.EVOKER = "EVOKER";
NS.HUNTER = "HUNTER";
NS.MAGE = "MAGE";
NS.MONK = "MONK";
NS.PALADIN = "PALADIN";
NS.PRIEST = "PRIEST";
NS.ROGUE = "ROGUE";
NS.SHAMAN = "SHAMAN";
NS.WARLOCK = "WARLOCK";
NS.WARRIOR = "WARRIOR";

-- For hiding timer by OmniCC
NS.HIDETIMEROMNICC = "BoopHideTimer";
